# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.tests(ignoreList=["sillyCentroid.cc", "sourceDetectionBickTmp.py", 
                                          "sourceMeasurementBickTmp.py"])
