# -*- python -*-
Import('env')

doxy = env.Doxygen("htmlDir", "doxygen.conf")
env.Ignore(doxy, Glob("../python/lsst/meas/algorithms/*_wrap.cc"))
env.Ignore(doxy, Glob("../python/lsst/meas/algorithms/*Lib.py"))

