# -*- python -*-
Import('env')
import glob
import os

env.SharedLibrary(
    'meas_algorithms',
    glob.glob("../src/*.cc") + glob.glob("../src/*/*.cc"),
    LIBS=filter(lambda p: p != "meas_algorithms", env.getlibs("meas_algorithms")),
)
