# -*- python -*-
Import('env')
import glob
import os

ccFiles = glob.glob("../src/*.cc") + glob.glob("../src/*/*.cc")
try:
    ccFiles = env.SourcesForSharedLibrary(ccFiles)
except AttributeError:                  # requires sconsUtils > 3.3
    pass

env.SharedLibrary(
    'meas_algorithms', ccFiles, LIBS=[x for x in env.getlibs("meas_algorithms") if x != "meas_algorithms"]
)
