# -*- python -*-
import sys
Import('env')

env.Program(["Centroid.cc"], LIBS=env.getlibs("meas_algorithms"))
env.Program(["CR.cc"], LIBS=env.getlibs("meas_algorithms"))
env.Program(["coeff.cc"], LIBS=env.getlibs("meas_algorithms"))
env.Program(["growthcurve.cc"], LIBS=env.getlibs("meas_algorithms","afw"))
env.Program(["psf.cc"], LIBS=env.getlibs("meas_algorithms","afw"))
