# -*- python -*-
Import("env")
import re
import lsst.SConsUtils as scons

env.CheckSwig("python", ilang="c++",
              includedProducts="utils daf_base daf_data daf_persistence pex_exceptions pex_logging pex_policy security afw")

env.LoadableModuleIncomplete("_algorithmsLib", Split("algorithmsLib.i"),
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs("meas_algorithms"))
