# -*- python -*-
from lsst.sconsUtils import scripts

scripts.BasicSConscript.python(['_algorithmsLib'], [
    '_algorithmsLib.cc',
    'cloughTocher2DInterpolatorUtils.cc',
    'cr.cc',
    'coaddBoundedField.cc',
    'coaddPsf/coaddPsf.cc',
    'coaddTransmissionCurve.cc',
    'doubleGaussianPsf.cc',
    'imagePsf.cc',
    'glintpy.cc',
    'interp.cc',
    'kernelPsf.cc',
    'pcaPsf.cc',
    'psfCandidate/psfCandidate.cc',
    'singleGaussianPsf.cc',
    'spatialModelPsf.cc',
    'warpedPsf.cc'])
